blogger/config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogger/app/models/article.rb
class Article < ApplicationRecord
  has_many :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  has_many :tags, through: :taggings
  has_many :comments
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end
  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|entered_tag| entered_tag.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

blogger/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blogger/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

blogger/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash.notice = "Article '#{@article.title}' created."
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "Article '#{@article.title}' destroyed. =("
    redirect_to :articles
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' updated!"
    redirect_to article_path(@article)
  end
end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    flash.notice = "Comment created!"
    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    puts tag_path(@tag)
    puts (@tag.id)
    puts tag_path(@tag)
    @tag.destroy()
    flash.notice = "Tag '#{@tag.name}' destroyed. =("
    redirect_to :tags
  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p class="comment_time"><%= comment.created_at %></p>
</div>

blogger/app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:thumb) %><br/>
    <% end %>
    <%= f.label :image, "Attach an Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render partial: 'form' %>

blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
  <%= link_to "Create a new article", new_article_path, class: "new_article" %>
  <%= link_to "View/edit tags", tags_path, class: "tag_path" %>

blogger/app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render partial: 'form' %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url(:medium) %><br/>
  <% end %>
</p>
<p><%= @article.body %></p>
<%= link_to "Edit this article", edit_article_path(@article) %><br />
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to "<< Back to articles list", articles_path %><br />
<%= link_to "Delete article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"} %>

blogger/app/views/comments/_form.html.erb
<h3>Post a comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

blogger/app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag), class: 'tag_name', id: "tag_#{tag.id}" %>
      <%= link_to "Delete tag", tag_path(tag), method: :delete, data: {confirm: "are you sure you want to delete this tag?"} %>
    </li>
  <% end %>
</ul>
<%= link_to "Back to articles", articles_path, class: "article_index" %>

blogger/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
<%= link_to "Delete tag", tag_path(@tag), method: :delete, data: {confirm: "are you sure you want to delete this tag?"} %>